# useful for testing purpuses, and when your docker doesn't supports multi-stage
# builds.

FROM golang:alpine

ENV target_dir /grafana

RUN mkdir -p $target_dir
WORKDIR $target_dir

RUN apk --no-cache add make git nano curl ca-certificates

COPY main.go ./
COPY Makefile ./

RUN go get -d -v && \
    CGO_ENABLED=0 GOOS=linux go build -v -a -installsuffix cgo -o grafana_bot

EXPOSE 9087

ENTRYPOINT ["./grafana_bot"]
